// Generated by CoffeeScript 1.4.0
(function() {

  $(document).ready(function() {
    var LOGGEDIN, login_fail, post_error, post_success, process_click, to_logged_in_state, to_logged_out_state;
    LOGGEDIN = false;
    $('.alert').hide();
    post_error = function(msg) {
      return $('.alert').addClass('alert-error').removeClass('alert-success').text(msg).slideDown();
    };
    post_success = function(msg) {
      return $('.alert').addClass('alert-success').removeClass('alert-error').text(msg).slideDown();
    };
    to_logged_in_state = function(user) {
      LOGGEDIN = true;
      $('.control-group').slideUp();
      $('#button').text('Get me outta here!').removeClass('btn-primary').addClass('btn-danger');
      post_success("Welcome back, " + user + "! You've been logged in.");
    };
    to_logged_out_state = function() {
      LOGGEDIN = false;
      $('.control-group').slideDown();
      $('#button').text('Get me in there!').removeClass('btn-danger').addClass('btn-primary');
      return $('.alert').slideUp();
    };
    login_fail = function() {
      return post_error("Sorry, you're username and/or password are incorrect.");
    };
    process_click = function() {
      var email, password;
      if (LOGGEDIN) {
        to_logged_out_state();
        return;
      }
      email = $('#email').val();
      password = $('#password').val();
      if (!email || !password) {
        post_error("Oops! Missing an email or a password?");
        return;
      }
      return $.ajax({
        type: 'GET',
        url: "http://randomlogin.dev/login",
        data: {
          user: email,
          pass: password
        },
        success: function(d) {
          return to_logged_in_state(email);
        },
        error: function(xhr, textStatus, errorThrown) {
          if (errorThrown === 'Unauthorized') {
            return login_fail();
          } else {
            console.log("The following error was thrown:");
            return console.log(errorThrown);
          }
        }
      });
    };
    return $('#button').click(function(e) {
      e.preventDefault();
      return process_click();
    });
  });

}).call(this);
